# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UDPFrame.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UDPFrame.proto',
  package='Protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0eUDPFrame.proto\x12\x08Protocol\"4\n\nConnection\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0c\n\x04Pass\x18\x03 \x01(\t\"$\n\tFrameInfo\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0b\n\x03Key\x18\x02 \x01(\t\"S\n\tFramePack\x12\r\n\x05\x46rame\x18\x01 \x01(\x05\x12&\n\tFrameList\x18\x02 \x03(\x0b\x32\x13.Protocol.FrameInfo\x12\x0f\n\x07MsgType\x18\x03 \x01(\x05\x62\x06proto3'
)




_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='Protocol.Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='Protocol.Connection.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='Protocol.Connection.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Pass', full_name='Protocol.Connection.Pass', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=80,
)


_FRAMEINFO = _descriptor.Descriptor(
  name='FrameInfo',
  full_name='Protocol.FrameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='Protocol.FrameInfo.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Key', full_name='Protocol.FrameInfo.Key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=118,
)


_FRAMEPACK = _descriptor.Descriptor(
  name='FramePack',
  full_name='Protocol.FramePack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Frame', full_name='Protocol.FramePack.Frame', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FrameList', full_name='Protocol.FramePack.FrameList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='Protocol.FramePack.MsgType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=203,
)

_FRAMEPACK.fields_by_name['FrameList'].message_type = _FRAMEINFO
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION
DESCRIPTOR.message_types_by_name['FrameInfo'] = _FRAMEINFO
DESCRIPTOR.message_types_by_name['FramePack'] = _FRAMEPACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTION,
  '__module__' : 'UDPFrame_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Connection)
  })
_sym_db.RegisterMessage(Connection)

FrameInfo = _reflection.GeneratedProtocolMessageType('FrameInfo', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEINFO,
  '__module__' : 'UDPFrame_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.FrameInfo)
  })
_sym_db.RegisterMessage(FrameInfo)

FramePack = _reflection.GeneratedProtocolMessageType('FramePack', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEPACK,
  '__module__' : 'UDPFrame_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.FramePack)
  })
_sym_db.RegisterMessage(FramePack)


# @@protoc_insertion_point(module_scope)
